FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci || npm install
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.http.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /var/www/acme /etc/nginx/tls
EXPOSE 80 443
